import React from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';

type MetaConfig = {
  [key: string]: {
    title: string;
  };
};

const metaConfig: MetaConfig = {
  '/': {
    title: 'd7holic',
  },
  '/about': {
    title: 'About',
  },
  '/contact': {
    title: 'Contact',
  },
  default: {
    title: '404',
  },
};

export default function Meta() {
  const router = useRouter();
  const meta = metaConfig[router.pathname] || metaConfig.default;

  return (
    <Head>
      <title>{meta.title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
