import React, { use } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head';

export default function Meta() {
    const router = useRouter();

    if(router.pathname == '/'){
        return(
            <Head>
                <title>Marlon Martin</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>  
        )
    }
  return (
    <Head>
        <title>404 Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head> 
  )
}
